services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: wdghkla123
    networks:
      - internal
      - default
    expose:
      - 27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: wdghkla123
      ME_CONFIG_MONGODB_URL: mongodb://root:wdghkla123@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - internal
      - default
    expose:
      - 8081

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: code-preview-server
    volumes:
      - .:/usr/app
    ports:
      - 5172:5172
    env_file:
      - path: ./.env
    environment:
      - TERM=xterm-256color
      - NODE_ENV=development
    networks:
      - internal
    expose:
      - 5172
    command: ["npm", "run", "dev"]

networks:
  internal:
  default:
